"""
core/pro_players_data.py — Big database of pro players
"""

PRO_PLAYERS = [
    {"name": "113", "team": "Team BDS", "region": "LEC", "role": "Jungle", "champs": ["Vi", "Jarvan IV"], "account": "113#ADS", "photo_url": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/13/BDS_113_2024_Split_1.png"},
    {"name": "1Jiang", "team": "Ultra Prime", "region": "LPL", "role": "Top", "champs": ["Aatrox", "Renekton"], "account": "1Jiang#CN1", "photo_url": ""},
    {"name": "1xn", "team": "THUNDERTALKGAMING", "region": "LPL", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "1xn#CN1", "photo_url": ""},
    {"name": "369", "team": "Top Esports", "region": "LPL", "role": "Top", "champs": ["Jax", "K'Sante"], "account": "369#Dice", "photo_url": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/4/4c/TES_369_2024_Split_1.png"},
    {"name": "Ackerman", "team": "Isurus Estral", "region": "LTAS", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Ackerman#LTA", "photo_url": ""},
    {"name": "Adam", "team": "Rogue", "region": "LEC", "role": "Top", "champs": ["Darius", "Olaf", "Garen"], "account": "Adam#LEC", "photo_url": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/c/c5/RGE_Adam_2024_Split_1.png"},
    {"name": "Aegis", "team": "RED Kalunga", "region": "LTAS", "role": "Jungle", "champs": ["Lee Sin", "Viego"], "account": "Aegis#BR1", "photo_url": ""},
    {"name": "Aiming", "team": "Dplus KIA", "region": "LCK", "role": "Bot", "champs": ["Zeri", "Aphelios"], "account": "Aiming#KR1", "photo_url": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/f6/DK_Aiming_2024_Split_1.png"},
    {"name": "Aki", "team": "SHENZHEN NINJAS IN PYJAMAS", "region": "LPL", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Aki#CN1", "photo_url": ""},
    {"name": "Ale", "team": "Beijing JDG Intel Esports", "region": "LPL", "role": "Top", "champs": ["Fiora", "Jax"], "account": "Ale#CN1", "photo_url": ""},
    {"name": "Alvaro", "team": "Movistar KOI", "region": "LEC", "role": "Support", "champs": ["Rell", "Nautilus"], "account": "MKOI Alvaro#KOI", "photo_url": ""},
    {"name": "Andil", "team": "DRX", "region": "LCK", "role": "Support", "champs": ["Braum", "Rakan"], "account": "Andil#KR1", "photo_url": ""},
    {"name": "Angel", "team": "SHANGHAI EDWARD GAMING HYCAN", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Angel#CN1", "photo_url": ""},
    {"name": "APA", "team": "Team Liquid Honda", "region": "LTAN", "role": "Mid", "champs": ["Ziggs", "Aurelion Sol"], "account": "APA#always", "photo_url": ""},
    {"name": "Aress", "team": "GAM Esports", "region": "LCP", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "Aress#LCP", "photo_url": ""},
    {"name": "Aria", "team": "DetonatioN FocusMe", "region": "LCP", "role": "Mid", "champs": ["Leblanc", "Ahri"], "account": "Aria#JP1", "photo_url": ""},
    {"name": "Artemis", "team": "GAM Esports", "region": "LCP", "role": "Bot", "champs": ["Xayah", "Kai'Sa"], "account": "Artemis#VCS", "photo_url": ""},
    {"name": "Ayu", "team": "FURIA", "region": "LTAS", "role": "Bot", "champs": ["Ezreal", "Lucian"], "account": "FUR Ayu#furia", "photo_url": ""},
    {"name": "Azhi", "team": "Talon", "region": "LCP", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "Azhi#PCS", "photo_url": ""},
    {"name": "Banderas", "team": "Rich Gang", "region": "NLC", "role": "Top", "champs": ["K'Sante", "Shen"], "account": "Banderas#NLC", "photo_url": ""},
    {"name": "bat", "team": "FunPlus Phoenix", "region": "LPL", "role": "Top", "champs": ["Jax", "Fiora"], "account": "bat#CN1", "photo_url": ""},
    {"name": "Baus", "team": "Los Ratones", "region": "NLC", "role": "Top", "champs": ["Sion", "Gragas"], "account": "Thebausffs#COOL", "photo_url": ""},
    {"name": "Bdd", "team": "kt Rolster", "region": "LCK", "role": "Mid", "champs": ["Azir", "Taliyah"], "account": "Bdd#KR1", "photo_url": ""},
    {"name": "Beichuan", "team": "THUNDERTALKGAMING", "region": "LPL", "role": "Jungle", "champs": ["Lee Sin", "Nidalee"], "account": "Beichuan#CN1", "photo_url": ""},
    {"name": "Berserker", "team": "DN FREECS", "region": "LCK", "role": "Bot", "champs": ["Zeri", "Lucian"], "account": "Berserker#KR1", "photo_url": ""},
    {"name": "BeryL", "team": "Dplus KIA", "region": "LCK", "role": "Support", "champs": ["Heimerdinger", "Bard"], "account": "BeryL#KR1", "photo_url": ""},
    {"name": "Betty", "team": "Talon", "region": "LCP", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Betty#PCS", "photo_url": ""},
    {"name": "Bin", "team": "BILIBILI GAMING DREAMSMART", "region": "LPL", "role": "Top", "champs": ["Jax", "Camille", "Fiora"], "account": "BLGBin ge#EUW", "photo_url": ""},
    {"name": "Bitse", "team": "DMG Esports", "region": "NLC", "role": "Mid", "champs": ["Orianna", "Syndra"], "account": "Bitse#NLC", "photo_url": ""},
    {"name": "Blaber", "team": "Cloud9 Kia", "region": "LTAN", "role": "Jungle", "champs": ["Olaf", "Kindred"], "account": "Blaber#NA1", "photo_url": ""},
    {"name": "Boal", "team": "Vivo Keyd Stars", "region": "LTAS", "role": "Top", "champs": ["Gnar", "Aatrox"], "account": "Boal#BR1", "photo_url": ""},
    {"name": "Bong", "team": "BBL Dark Passage", "region": "TCL", "role": "Top", "champs": ["Renekton", "Jayce"], "account": "Bong#TCL", "photo_url": ""},
    {"name": "Brance", "team": "RED Kalunga", "region": "LTAS", "role": "Bot", "champs": ["Lucian", "Draven"], "account": "Brance#Branc", "photo_url": ""},
    {"name": "Breathe", "team": "Weibo Gaming Faw Audi", "region": "LPL", "role": "Top", "champs": ["Fiora", "Jax"], "account": "WB Breathe#WBG", "photo_url": ""},
    {"name": "BrokenBlade", "team": "G2 Esports", "region": "LEC", "role": "Top", "champs": ["Renekton", "Darius"], "account": "BrokenBlade#LEC", "photo_url": ""},
    {"name": "Buchi", "team": "DMG Esports", "region": "NLC", "role": "Jungle", "champs": ["Jarvan IV", "Vi"], "account": "Buchi#NLC", "photo_url": ""},
    {"name": "BuLLDoG", "team": "DN FREECS", "region": "LCK", "role": "Mid", "champs": ["Taliyah", "Azir"], "account": "BuLLDoG#KR1", "photo_url": ""},
    {"name": "Bvoy", "team": "Shopify Rebellion", "region": "LTAN", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Bvoy#NA1", "photo_url": ""},
    {"name": "Bwipo", "team": "FlyQuest", "region": "LTAN", "role": "Top", "champs": ["Aatrox", "Gwen"], "account": "Bwipo#NA1", "photo_url": ""},
    {"name": "Caliste", "team": "Karmine Corp", "region": "LEC", "role": "Bot", "champs": ["Kalista", "Draven"], "account": "Caliste#LEC", "photo_url": ""},
    {"name": "Calmsky", "team": "DMG Esports", "region": "NLC", "role": "Bot", "champs": ["Jhin", "Ezreal"], "account": "Calmsky#NLC", "photo_url": ""},
    {"name": "Canyon", "team": "Gen.G Esports", "region": "LCK", "role": "Jungle", "champs": ["Nidalee", "Graves", "Lee Sin"], "account": "허거덩#0303", "photo_url": ""},
    {"name": "Caps", "team": "G2 Esports", "region": "LEC", "role": "Mid", "champs": ["LeBlanc", "Azir", "Sylas"], "account": "G2 Caps#1323", "photo_url": ""},
    {"name": "Care", "team": "FunPlus Phoenix", "region": "LPL", "role": "Mid", "champs": ["Akali", "Yone"], "account": "Care#CN1", "photo_url": ""},
    {"name": "CarioK", "team": "paiN Gaming", "region": "LTAS", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "CarioK#BR1", "photo_url": ""},
    {"name": "Carzzy", "team": "Team Vitality", "region": "LEC", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "Carzzy#LEC", "photo_url": ""},
    {"name": "Castle", "team": "Disguised", "region": "LTAN", "role": "Top", "champs": ["K'Sante", "Gwen"], "account": "Castle#LTA", "photo_url": ""},
    {"name": "Ceos", "team": "Shopify Rebellion", "region": "LTAN", "role": "Support", "champs": ["Nautilus", "Rakan"], "account": "Ceos#LTA", "photo_url": ""},
    {"name": "Chovy", "team": "Gen.G Esports", "region": "LCK", "role": "Mid", "champs": ["Azir", "Corky", "Yone"], "account": "Chovy#KR1", "photo_url": ""},
    {"name": "Clear", "team": "BNK FEARX", "region": "LCK", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Clear#KR1", "photo_url": ""},
    {"name": "Clozer", "team": "OKSavingsBank BRION", "region": "LCK", "role": "Mid", "champs": ["Akali", "Irelia"], "account": "Clozer#KR1", "photo_url": ""},
    {"name": "Contractz", "team": "Shopify Rebellion", "region": "LTAN", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Contractz#NA1", "photo_url": ""},
    {"name": "CoreJJ", "team": "Team Liquid Honda", "region": "LTAN", "role": "Support", "champs": ["Thresh", "Rakan"], "account": "리퀴드 코어장전#KR1", "photo_url": ""},
    {"name": "Courage", "team": "Fukuoka SoftBank HAWKS gaming", "region": "LCP", "role": "Top", "champs": ["Renekton", "Gnar"], "account": "Courage#JP1", "photo_url": ""},
    {"name": "Creme", "team": "Top Esports", "region": "LPL", "role": "Mid", "champs": ["Akali", "Sylas"], "account": "Creme#CN1", "photo_url": ""},
    {"name": "Crisp", "team": "Top Esports", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Renata Glasc"], "account": "Crisp#CN1", "photo_url": ""},
    {"name": "Crownie", "team": "Los Ratones", "region": "NLC", "role": "Bot", "champs": ["Ezreal", "Jinx"], "account": "LR Crownie#LRAT", "photo_url": ""},
    {"name": "Cube", "team": "Xi'an Team WE", "region": "LPL", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "Cube#CN1", "photo_url": ""},
    {"name": "Cuzz", "team": "kt Rolster", "region": "LCK", "role": "Jungle", "champs": ["Sejuani", "Vi"], "account": "Cuzz#KR1", "photo_url": ""},
    {"name": "Czajek", "team": "Team Vitality", "region": "LEC", "role": "Mid", "champs": ["Syndra", "Orianna"], "account": "Czajek#LEC", "photo_url": ""},
    {"name": "Czekolad", "team": "Barça Esports", "region": "EMEA", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Czekolad#EUW", "photo_url": ""},
    {"name": "Daglas", "team": "Los Heretics", "region": "EMEA", "role": "Jungle", "champs": ["Lee Sin", "Viego"], "account": "PL Canyon#HRTS", "photo_url": ""},
    {"name": "Delight", "team": "Hanwha Life Esports", "region": "LCK", "role": "Support", "champs": ["Rakan", "Nautilus"], "account": "플레이리스트겨울#KR1", "photo_url": ""},
    {"name": "DenVoksne", "team": "Unicorns of Love Sexy Edition", "region": "EMEA", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "DenVoksne#UOL", "photo_url": ""},
    {"name": "Diable", "team": "BNK FEARX", "region": "LCK", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Diable#KR1", "photo_url": ""},
    {"name": "Disamis", "team": "Vivo Keyd Stars", "region": "LTAS", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Disamis#BR1", "photo_url": ""},
    {"name": "Doggo", "team": "CTBC Flying Oyster", "region": "LCP", "role": "Bot", "champs": ["Tristana", "Zeri"], "account": "Doggo#CFO", "photo_url": ""},
    {"name": "Doinb", "team": "SHENZHEN NINJAS IN PYJAMAS", "region": "LPL", "role": "Mid", "champs": ["Ryze", "Galio"], "account": "Doinb#CN1", "photo_url": ""},
    {"name": "Doran", "team": "T1", "region": "LCK", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Doran#KR1", "photo_url": ""},
    {"name": "Drakehero", "team": "Fluxo W7M", "region": "LTAS", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "Drakehero#BR1", "photo_url": ""},
    {"name": "Driver", "team": "CTBC Flying Oyster", "region": "LCP", "role": "Top", "champs": ["K'Sante", "Renekton"], "account": "Driver#PCS", "photo_url": ""},
    {"name": "DuDu", "team": "DN FREECS", "region": "LCK", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "DuDu#KR1", "photo_url": ""},
    {"name": "Duro", "team": "Gen.G Esports", "region": "LCK", "role": "Support", "champs": ["Rakan", "Leona"], "account": "Duro#Gen", "photo_url": ""},
    {"name": "dyNquedo", "team": "paiN Gaming", "region": "LTAS", "role": "Mid", "champs": ["Azir", "Sylas"], "account": "dyNquedo#BR1", "photo_url": ""},
    {"name": "Eddie", "team": "Team Secret Whales", "region": "LCP", "role": "Bot", "champs": ["Xayah", "Kai'Sa"], "account": "Eddie#VCS", "photo_url": ""},
    {"name": "Elijah", "team": "Venomcrest", "region": "NLC", "role": "Jungle", "champs": ["Jarvan IV", "Vi"], "account": "Elijah#NLC", "photo_url": ""},
    {"name": "Elio", "team": "GAM Esports", "region": "LCP", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "Elio#0711", "photo_url": ""},
    {"name": "Elk", "team": "Bilibili Gaming", "region": "LPL", "role": "Bot", "champs": ["Zeri", "Lucian"], "account": "Elk#CN1", "photo_url": ""},
    {"name": "Elyoya", "team": "Movistar KOI", "region": "LEC", "role": "Jungle", "champs": ["Vi", "Lee Sin"], "account": "Elyoya#KOI", "photo_url": ""},
    {"name": "Emo", "team": "GAM Esports", "region": "LCP", "role": "Mid", "champs": ["Ahri", "Orianna"], "account": "Emo#VCS", "photo_url": ""},
    {"name": "eskii", "team": "Rich Gang", "region": "NLC", "role": "Mid", "champs": ["Syndra", "Orianna"], "account": "eskii#NLC", "photo_url": ""},
    {"name": "Exofeng", "team": "Bulldog Esports", "region": "NLC", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Exofeng#NLC", "photo_url": ""},
    {"name": "Eyla", "team": "100 Thieves", "region": "LTAN", "role": "Support", "champs": ["Rakan", "Thresh"], "account": "Eyla#LTA", "photo_url": ""},
    {"name": "Faetski", "team": "DMG Esports", "region": "NLC", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Faetski#NLC", "photo_url": ""},
    {"name": "FATE", "team": "Fukuoka SoftBank HAWKS gaming", "region": "LCP", "role": "Mid", "champs": ["Azir", "Syndra"], "account": "FATE#JP1", "photo_url": ""},
    {"name": "FBI", "team": "100 Thieves", "region": "LTAN", "role": "Bot", "champs": ["Lucian", "Kai'Sa"], "account": "FBI#LTA", "photo_url": ""},
    {"name": "Feather", "team": "THUNDERTALKGAMING", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Braum"], "account": "Feather#CN1", "photo_url": ""},
    {"name": "Fisher", "team": "NONGSHIM RED FORCE", "region": "LCK", "role": "Mid", "champs": ["Ahri", "Sylas"], "account": "Fisher#KR1", "photo_url": ""},
    {"name": "Flakked", "team": "Team Heretics", "region": "LEC", "role": "Bot", "champs": ["Xayah", "Kai'Sa"], "account": "Flakked#LEC", "photo_url": ""},
    {"name": "Flandre", "team": "Anyone's Legend", "region": "LPL", "role": "Top", "champs": ["Jayce", "Fiora"], "account": "Flandre#CN1", "photo_url": ""},
    {"name": "fNb", "team": "RED Kalunga", "region": "LTAS", "role": "Top", "champs": ["Gnar", "Aatrox"], "account": "fNb#BR1", "photo_url": ""},
    {"name": "FoFo", "team": "Talon", "region": "LCP", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "FoFo#PCS", "photo_url": ""},
    {"name": "Fornoreason", "team": "Unicorns of Love Sexy Edition", "region": "EMEA", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "Fornoreason#EUW", "photo_url": ""},
    {"name": "frosty", "team": "RED Kalunga", "region": "LTAS", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "frosty#BR1", "photo_url": ""},
    {"name": "Fudge", "team": "Shopify Rebellion", "region": "LTAN", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "Fudge#NA1", "photo_url": ""},
    {"name": "Fuuu", "team": "Fluxo W7M", "region": "LTAS", "role": "Mid", "champs": ["Azir", "Sylas"], "account": "Fuuu#BR1", "photo_url": ""},
    {"name": "Gaeng", "team": "Fukuoka SoftBank HAWKS gaming", "region": "LCP", "role": "Support", "champs": ["Leona", "Nautilus"], "account": "Gaeng#JP1", "photo_url": ""},
    {"name": "GALA", "team": "Invictus Gaming", "region": "LPL", "role": "Bot", "champs": ["Kai'Sa", "Xayah"], "account": "GALA#CN1", "photo_url": ""},
    {"name": "GIDEON", "team": "NONGSHIM RED FORCE", "region": "LCK", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "GIDEON#KR1", "photo_url": ""},
    {"name": "Grevthar", "team": "RED Kalunga", "region": "LTAS", "role": "Mid", "champs": ["Azir", "Sylas"], "account": "Grevthar#BR1", "photo_url": ""},
    {"name": "Guigo", "team": "FURIA", "region": "LTAS", "role": "Top", "champs": ["Gnar", "Fiora"], "account": "Guigo#BR1", "photo_url": ""},
    {"name": "Guigs", "team": "Fluxo W7M", "region": "LTAS", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Guigs#BR1", "photo_url": ""},
    {"name": "Gury", "team": "MGN Vikings Esports", "region": "LCP", "role": "Jungle", "champs": ["Vi", "Jarvan IV"], "account": "Gury#VCS", "photo_url": ""},
    {"name": "Hang", "team": "WeiboGaming Faw Audi", "region": "LPL", "role": "Support", "champs": ["Rakan", "Nautilus"], "account": "Hang#CN1", "photo_url": ""},
    {"name": "Harbo", "team": "Lundqvist Lightside", "region": "NLC", "role": "Mid", "champs": ["Orianna", "Syndra"], "account": "Harbo#NLC", "photo_url": ""},
    {"name": "Harp", "team": "DetonatioN FocusMe", "region": "LCP", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "Harp#JP1", "photo_url": ""},
    {"name": "Hena", "team": "LYON", "region": "LTAN", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Hena#LTA", "photo_url": ""},
    {"name": "Heng", "team": "Oh My God", "region": "LPL", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Heng#CN1", "photo_url": ""},
    {"name": "Hery", "team": "Oh My God", "region": "LPL", "role": "Top", "champs": ["K'Sante", "Renekton"], "account": "Hery#CN1", "photo_url": ""},
    {"name": "Hidan", "team": "Fluxo W7M", "region": "LTAS", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Hidan#BR1", "photo_url": ""},
    {"name": "Hiro02", "team": "Team Secret Whales", "region": "LCP", "role": "Mid", "champs": ["Ahri", "Azir"], "account": "Hiro02#VCS", "photo_url": ""},
    {"name": "Hizto", "team": "Team Secret Whales", "region": "LCP", "role": "Top", "champs": ["K'Sante", "Renekton"], "account": "Hizto#VCS", "photo_url": ""},
    {"name": "HongQ", "team": "CTBC Flying Oyster", "region": "LCP", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "HongQ#PCS", "photo_url": ""},
    {"name": "Hope", "team": "Anyone's Legend", "region": "LPL", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Hope#CN1", "photo_url": ""},
    {"name": "Humanoid", "team": "Fnatic", "region": "LEC", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Humanoid#LEC", "photo_url": ""},
    {"name": "Humzh", "team": "The Ruddy Sack", "region": "NLC", "role": "Bot", "champs": ["Jinx", "Ezreal"], "account": "Humzh#NLC", "photo_url": ""},
    {"name": "Hustlin", "team": "The Ruddy Sack", "region": "NLC", "role": "Support", "champs": ["Thresh", "Blitzcrank"], "account": "Hustlin#NLC", "photo_url": ""},
    {"name": "Impact", "team": "Team Liquid Honda", "region": "LTAN", "role": "Top", "champs": ["Jax", "Gnar"], "account": "Impact#NA1", "photo_url": ""},
    {"name": "Inspired", "team": "FlyQuest", "region": "LTAN", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Inspired#NA1", "photo_url": ""},
    {"name": "Irrelevant", "team": "Team BDS", "region": "LEC", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Irrelevant#LEC", "photo_url": ""},
    {"name": "Isles", "team": "Dignitas", "region": "LTAN", "role": "Support", "champs": ["Thresh", "Rakan"], "account": "Isles#NA1", "photo_url": ""},
    {"name": "ISMA", "team": "SK Gaming", "region": "LEC", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "ISMA#LEC", "photo_url": ""},
    {"name": "JackeyLove", "team": "Top Esports", "region": "LPL", "role": "Bot", "champs": ["Draven", "Kai'Sa"], "account": "JackeyLove#CN1", "photo_url": ""},
    {"name": "Jackies", "team": "GIANTX", "region": "LEC", "role": "Mid", "champs": ["Ahri", "Taliyah"], "account": "Jackies#LEC", "photo_url": ""},
    {"name": "Jankos", "team": "The Ruddy Sack", "region": "NLC", "role": "Jungle", "champs": ["Lee Sin", "Sejuani"], "account": "Jankos#NLC", "photo_url": ""},
    {"name": "Jcom", "team": "Team Secret Whales", "region": "LCP", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Jcom#VCS", "photo_url": ""},
    {"name": "Jensen", "team": "Dignitas", "region": "LTAN", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Jensen#NA1", "photo_url": ""},
    {"name": "Jezu", "team": "Galions", "region": "EMEA", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "Jezu#EUW", "photo_url": ""},
    {"name": "JieJie", "team": "Invictus Gaming", "region": "LPL", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "JieJie#CN1", "photo_url": ""},
    {"name": "Jiwoo", "team": "NONGSHIM RED FORCE", "region": "LCK", "role": "Bot", "champs": ["Zeri", "Jinx"], "account": "Jiwoo#KR1", "photo_url": ""},
    {"name": "JNX", "team": "SK Gaming", "region": "LEC", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "JNX#LEC", "photo_url": ""},
    {"name": "JoJo", "team": "FURIA", "region": "LTAS", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "JoJo#BR1", "photo_url": ""},
    {"name": "Jojopyun", "team": "Movistar KOI", "region": "LEC", "role": "Mid", "champs": ["Azir", "Akali"], "account": "Jojopyun#LAN", "photo_url": ""},
    {"name": "Josedeodo", "team": "Isurus Estral", "region": "LTAS", "role": "Jungle", "champs": ["Lee Sin", "Viego"], "account": "Josedeodo#NA12", "photo_url": ""},
    {"name": "Junhao", "team": "Ultra Prime", "region": "LPL", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Junhao#CN1", "photo_url": ""},
    {"name": "JunJia", "team": "CTBC Flying Oyster", "region": "LCP", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "庭不下來#0610", "photo_url": ""},
    {"name": "Kael", "team": "Anyone's Legend", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Rakan"], "account": "Kael#CN1", "photo_url": ""},
    {"name": "Kaiser", "team": "Los Heretics", "region": "EMEA", "role": "Support", "champs": ["Rakan", "Leona"], "account": "Kaiser#LEC", "photo_url": ""},
    {"name": "Kaiwing", "team": "CTBC Flying Oyster", "region": "LCP", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "Kaiwing#PCS", "photo_url": ""},
    {"name": "Kamiloo", "team": "Team Heretics", "region": "LEC", "role": "Mid", "champs": ["Ahri", "Orianna"], "account": "Kamiloo#LEC", "photo_url": ""},
    {"name": "Kanavi", "team": "TopEsports", "region": "LPL", "role": "Jungle", "champs": ["Lee Sin", "Nidalee"], "account": "Kanavi#CN1", "photo_url": ""},
    {"name": "Karis", "team": "Xi'an Team WE", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Karis#CN1", "photo_url": ""},
    {"name": "Karsa", "team": "Talon", "region": "LCP", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Karsa#PCS", "photo_url": ""},
    {"name": "Kasing", "team": "Bulldog Esports", "region": "NLC", "role": "Support", "champs": ["Thresh", "Rakan"], "account": "Kasing#NLC", "photo_url": ""},
    {"name": "Kati", "team": "MGN Vikings Esports", "region": "LCP", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Kati#VCS", "photo_url": ""},
    {"name": "Kaymin", "team": "Bulldog Esports", "region": "NLC", "role": "Mid", "champs": ["Syndra", "Orianna"], "account": "Kaymin#NLC", "photo_url": ""},
    {"name": "Kellin", "team": "BNK FEARX", "region": "LCK", "role": "Support", "champs": ["Lulu", "Karma"], "account": "Kellin#KR1", "photo_url": ""},
    {"name": "Keria", "team": "T1", "region": "LCK", "role": "Support", "champs": ["Thresh", "Nautilus", "Lux"], "account": "T1 Keria#5252", "photo_url": ""},
    {"name": "Kiaya", "team": "GAM Esports", "region": "LCP", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "cokhinaocokhinao#kiaya", "photo_url": ""},
    {"name": "Kiin", "team": "Gen.G Esports", "region": "LCK", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "Kiin#KR1", "photo_url": ""},
    {"name": "Kiki", "team": "Venomcrest", "region": "NLC", "role": "Support", "champs": ["Leona", "Nautilus"], "account": "Kiki#NLC", "photo_url": ""},
    {"name": "Kingen", "team": "NONGSHIM RED FORCE", "region": "LCK", "role": "Top", "champs": ["Aatrox", "Gnar"], "account": "Kingen#KR1", "photo_url": ""},
    {"name": "knight", "team": "Bilibili Gaming", "region": "LPL", "role": "Mid", "champs": ["Syndra", "Jayce"], "account": "Knight#CN1", "photo_url": ""},
    {"name": "Kofte", "team": "BBL Dark Passage", "region": "TCL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Kofte#TCL", "photo_url": ""},
    {"name": "Kratos", "team": "MGN Vikings Esports", "region": "LCP", "role": "Top", "champs": ["K'Sante", "Renekton"], "account": "Kratos#VCS", "photo_url": ""},
    {"name": "Labrov", "team": "G2 Esports", "region": "LEC", "role": "Support", "champs": ["Rell", "Nautilus"], "account": "Labrov#LEC", "photo_url": ""},
    {"name": "Larssen", "team": "Rogue", "region": "LEC", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Larssen#LEC", "photo_url": ""},
    {"name": "Leave", "team": "SHENZHEN NINJAS IN PYJAMAS", "region": "LPL", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Leave#CN1", "photo_url": ""},
    {"name": "Legolas", "team": "Barça Esports", "region": "EMEA", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "Legolas#EUW", "photo_url": ""},
    {"name": "Lehends", "team": "NONGSHIM RED FORCE", "region": "LCK", "role": "Support", "champs": ["Rakan", "Lulu"], "account": "Lehends#원숭이", "photo_url": ""},
    {"name": "Lele", "team": "Royal Never Give Up", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Braum"], "account": "Lele#CN1", "photo_url": ""},
    {"name": "LeoLeCargo", "team": "Lundqvist Lightside", "region": "NLC", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "TDS LéoLeCargo#2706", "photo_url": ""},
    {"name": "Levi", "team": "GAM Esports", "region": "LCP", "role": "Jungle", "champs": ["Lee Sin", "Kha'Zix"], "account": "Levi#eXo", "photo_url": ""},
    {"name": "Licorice", "team": "LYON", "region": "LTAN", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "Licorice#NA1", "photo_url": ""},
    {"name": "LIDER", "team": "The Ruddy Sack", "region": "NLC", "role": "Mid", "champs": ["Akali", "Yone", "Zed"], "account": "LIDER#NLC", "photo_url": ""},
    {"name": "Life", "team": "DN FREECS", "region": "LCK", "role": "Support", "champs": ["Rakan", "Sett"], "account": "Life#KR1", "photo_url": ""},
    {"name": "Light", "team": "Weibo Gaming Faw Audi", "region": "LPL", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Light#CN1", "photo_url": ""},
    {"name": "Linfeng", "team": "Oh My God", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Braum"], "account": "Linfeng#CN1", "photo_url": ""},
    {"name": "Lofti", "team": "Venomcrest", "region": "NLC", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "Lofti#NLC", "photo_url": ""},
    {"name": "Lot", "team": "GIANTX", "region": "LEC", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "Lot#LEC", "photo_url": ""},
    {"name": "Lucid", "team": "Dplus KIA", "region": "LCK", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Lucid#KR1", "photo_url": ""},
    {"name": "Lulas", "team": "Bulldog Esports", "region": "NLC", "role": "Bot", "champs": ["Jhin", "Ezreal"], "account": "Lulas#NLC", "photo_url": ""},
    {"name": "Lyncas", "team": "Team Vitality", "region": "LEC", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Lyncas#LEC", "photo_url": ""},
    {"name": "Malrang", "team": "Rogue", "region": "LEC", "role": "Jungle", "champs": ["Jarvan IV", "Sejuani"], "account": "Malrang#LEC", "photo_url": ""},
    {"name": "Massu", "team": "FlyQuest", "region": "LTAN", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Massu#NA1", "photo_url": ""},
    {"name": "Mauki", "team": "Venomcrest", "region": "NLC", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Mauki#999", "photo_url": ""},
    {"name": "Meiko", "team": "Invictus Gaming", "region": "LPL", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "Meiko#CN1", "photo_url": ""},
    {"name": "Mietek", "team": "Bulldog Esports", "region": "NLC", "role": "Jungle", "champs": ["Vi", "Jarvan IV"], "account": "Mietek#NLC", "photo_url": ""},
    {"name": "Mikyx", "team": "Fnatic", "region": "LEC", "role": "Support", "champs": ["Bard", "Thresh"], "account": "Billy Butcher#Mikyx", "photo_url": ""},
    {"name": "Milan", "team": "DetonatioN FocusMe", "region": "LCP", "role": "Bot", "champs": ["Ezreal", "Aphelios"], "account": "Milan#JP1", "photo_url": ""},
    {"name": "MISSING", "team": "Beijing JDG Intel Esports", "region": "LPL", "role": "Support", "champs": ["Rakan", "Nautilus"], "account": "MISSING#CN1", "photo_url": ""},
    {"name": "Moham", "team": "Oh My God", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Braum"], "account": "Moham#CN1", "photo_url": ""},
    {"name": "Morgan", "team": "OKSavingsBank BRION", "region": "LCK", "role": "Top", "champs": ["Renekton", "Jax"], "account": "Morgan#KR1", "photo_url": ""},
    {"name": "Morttheus", "team": "Vivo Keyd Stars", "region": "LTAS", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "Morttheus#BR1", "photo_url": ""},
    {"name": "Myrwn", "team": "Movistar KOI", "region": "LEC", "role": "Top", "champs": ["Gwen", "K'Sante"], "account": "Myrwn#LEC", "photo_url": ""},
    {"name": "Nemesis", "team": "Los Ratones", "region": "NLC", "role": "Mid", "champs": ["Kassadin", "Kayle"], "account": "Nemesis#EUW", "photo_url": ""},
    {"name": "Neon", "team": "Beşiktaş Esports", "region": "TCL", "role": "Bot", "champs": ["Xayah", "Kai'Sa"], "account": "Neon#TCL", "photo_url": ""},
    {"name": "Nomi", "team": "Rich Gang", "region": "NLC", "role": "Support", "champs": ["Lulu", "Thresh"], "account": "Nomi#NLC", "photo_url": ""},
    {"name": "NoName", "team": "Verdant", "region": "NLC", "role": "Jungle", "champs": ["Jarvan IV", "Vi"], "account": "NoName#NLC", "photo_url": ""},
    {"name": "nuc", "team": "Team BDS", "region": "LEC", "role": "Mid", "champs": ["Azir", "Taliyah"], "account": "BDS nuc#BDS", "photo_url": ""},
    {"name": "Obstinatus", "team": "Verdant", "region": "NLC", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Obstinatus#999", "photo_url": ""},
    {"name": "ON", "team": "Bilibili Gaming", "region": "LPL", "role": "Support", "champs": ["Rakan", "Lulu"], "account": "ON#CN1", "photo_url": ""},
    {"name": "Oner", "team": "T1", "region": "LCK", "role": "Jungle", "champs": ["Lee Sin", "Vi", "Nidalee"], "account": "오 너#111", "photo_url": ""},
    {"name": "Oscarinin", "team": "Fnatic", "region": "LEC", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Oscarinin#LEC", "photo_url": ""},
    {"name": "Palafox", "team": "Shopify Rebellion", "region": "LTAN", "role": "Mid", "champs": ["Taliyah", "Ahri"], "account": "Palafox#NA1", "photo_url": ""},
    {"name": "Papiteero", "team": "Verdant", "region": "NLC", "role": "Mid", "champs": ["Orianna", "Syndra"], "account": "Papiteero#NLC", "photo_url": ""},
    {"name": "Parus", "team": "Team BDS", "region": "LEC", "role": "Support", "champs": ["Rell", "Nautilus"], "account": "Parus#LEC", "photo_url": ""},
    {"name": "Patrik", "team": "Rogue", "region": "LEC", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Patrik#LEC", "photo_url": ""},
    {"name": "Peanut", "team": "Hanwha Life Esports", "region": "LCK", "role": "Jungle", "champs": ["Lee Sin", "Maokai", "Vi"], "account": "HLE Peanut#2001", "photo_url": ""},
    {"name": "PerfecT", "team": "kt Rolster", "region": "LCK", "role": "Top", "champs": ["Gnar", "K'Sante"], "account": "KT PerfecT#2004", "photo_url": ""},
    {"name": "Perkz", "team": "The Ruddy Sack", "region": "NLC", "role": "Mid", "champs": ["LeBlanc", "Azir"], "account": "Perkz#91636", "photo_url": ""},
    {"name": "Peyz", "team": "Beijing JDG Intel Esports", "region": "LPL", "role": "Bot", "champs": ["Zeri", "Kai'Sa"], "account": "Peyz#CN1", "photo_url": ""},
    {"name": "Photic", "team": "Suzhou LNG Ninebot Esports", "region": "LPL", "role": "Bot", "champs": ["Aphelios", "Lucian"], "account": "Photic#CN1", "photo_url": ""},
    {"name": "Photon", "team": "Beşiktaş Esports", "region": "TCL", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "Photon#TCL", "photo_url": ""},
    {"name": "Pollu", "team": "OKSavingsBank BRION", "region": "LCK", "role": "Support", "champs": ["Leona", "Braum"], "account": "Pollu#KR1", "photo_url": ""},
    {"name": "ppgod", "team": "SHENZHEN NINJAS IN PYJAMAS", "region": "LPL", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "ppgod#CN1", "photo_url": ""},
    {"name": "Pyosik", "team": "DN FREECS", "region": "LCK", "role": "Jungle", "champs": ["Kindred", "Lee Sin"], "account": "DNS Pyosik#KR2", "photo_url": ""},
    {"name": "Quad", "team": "FlyQuest", "region": "LTAN", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "FLY Quad#123", "photo_url": ""},
    {"name": "Quid", "team": "100 Thieves", "region": "LTAN", "role": "Mid", "champs": ["Taliyah", "Ahri"], "account": "Quid#NA1", "photo_url": ""},
    {"name": "Ragner", "team": "Galions", "region": "EMEA", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "Ragner#EUW", "photo_url": ""},
    {"name": "Raptor", "team": "BNK FEARX", "region": "LCK", "role": "Jungle", "champs": ["Vi", "Jarvan IV"], "account": "Raptor#KR1", "photo_url": ""},
    {"name": "RayFarky", "team": "DetonatioN FocusMe", "region": "LCP", "role": "Top", "champs": ["Jax", "Fiora"], "account": "RayFarky#JP1", "photo_url": ""},
    {"name": "Razork", "team": "Fnatic", "region": "LEC", "role": "Jungle", "champs": ["Vi", "Lee Sin"], "account": "Razork#LEC", "photo_url": ""},
    {"name": "Rekkles", "team": "Los Ratones", "region": "NLC", "role": "Support", "champs": ["Thresh", "Janna"], "account": "Rekkles#1996", "photo_url": ""},
    {"name": "Rest", "team": "CTBC Flying Oyster", "region": "LCP", "role": "Top", "champs": ["Renekton", "Gnar"], "account": "Rest#PCS", "photo_url": ""},
    {"name": "Rich", "team": "DRX", "region": "LCK", "role": "Top", "champs": ["Aatrox", "Gnar"], "account": "Rich#KR1", "photo_url": ""},
    {"name": "Rin", "team": "Los Heretics", "region": "EMEA", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Rin#LEC", "photo_url": ""},
    {"name": "River", "team": "100 Thieves", "region": "LTAN", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "River#NA1", "photo_url": ""},
    {"name": "Robo", "team": "LOUD", "region": "LTAS", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "Robo#BR1", "photo_url": ""},
    {"name": "Ronaldo", "team": "Verdant", "region": "NLC", "role": "Mid", "champs": ["Orianna", "Syndra"], "account": "Ronaldo#NLC", "photo_url": ""},
    {"name": "Rookie", "team": "Invictus Gaming", "region": "LPL", "role": "Mid", "champs": ["Orianna", "Syndra"], "account": "Rookie#CN1", "photo_url": ""},
    {"name": "Rosielove", "team": "Ultra Prime", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Braum"], "account": "Rosielove#CN1", "photo_url": ""},
    {"name": "Ruler", "team": "Gen.G Esports", "region": "LCK", "role": "Bot", "champs": ["Xayah", "Aphelios"], "account": "Ruler#KR1", "photo_url": ""},
    {"name": "RustySniper", "team": "Lundqvist Lightside", "region": "NLC", "role": "Top", "champs": ["Gnar", "Jax"], "account": "RustySniper#NLC", "photo_url": ""},
    {"name": "Rutzou", "team": "KAOS Esport", "region": "NLC", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Rutzou#NLC", "photo_url": ""},
    {"name": "Saber", "team": "Ultra Prime", "region": "LPL", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Saber#CN1", "photo_url": ""},
    {"name": "Saint", "team": "LYON", "region": "LTAN", "role": "Support", "champs": ["Thresh", "Rakan"], "account": "Saint#LTA", "photo_url": ""},
    {"name": "SAJATOR", "team": "Los Heretics", "region": "EMEA", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "SAJATOR#LEC", "photo_url": ""},
    {"name": "Santorin", "team": "Team NORD", "region": "NLC", "role": "Jungle", "champs": ["Lee Sin", "Sejuani"], "account": "Santorin#NLC", "photo_url": ""},
    {"name": "ScaryJerry", "team": "Disguised", "region": "NAC", "role": "Bot", "champs": ["Jinx", "Ezreal"], "account": "ScaryJerry#NA1", "photo_url": ""},
    {"name": "Scout", "team": "JDG Intel Esports", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Scout#CN1", "photo_url": ""},
    {"name": "seaz", "team": "Unicorns of Love Sexy Edition", "region": "EMEA", "role": "Support", "champs": ["Rakan", "Thresh"], "account": "seaz#EUW", "photo_url": ""},
    {"name": "SeTab", "team": "THUNDERTALKGAMING", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "SeTab#CN1", "photo_url": ""},
    {"name": "Shad0w", "team": "FunPlus Phoenix", "region": "LPL", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Shad0w#CN1", "photo_url": ""},
    {"name": "shanji", "team": "SHENZHEN NINJAS IN PYJAMAS", "region": "LPL", "role": "Top", "champs": ["K'Sante", "Renekton"], "account": "shanji#CN1", "photo_url": ""},
    {"name": "Shanks", "team": "Anyone's Legend", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Shanks#CN1", "photo_url": ""},
    {"name": "Shaoye", "team": "LGD Gaming", "region": "LPL", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Shaoye#CN1", "photo_url": ""},
    {"name": "sheer", "team": "Beijing JDG Intel Esports", "region": "LPL", "role": "Top", "champs": ["Gnar", "Jax"], "account": "sheer#CN1", "photo_url": ""},
    {"name": "Sheiden", "team": "Dignitas", "region": "LTAN", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Sheiden#NA1", "photo_url": ""},
    {"name": "Sheo", "team": "Team Heretics", "region": "LEC", "role": "Jungle", "champs": ["Vi", "Maokai"], "account": "Sheo#LEC", "photo_url": ""},
    {"name": "Shogun", "team": "MGN Vikings Esports", "region": "LCP", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Shogun#VCS", "photo_url": ""},
    {"name": "Simpli", "team": "Unicorns of Love Sexy Edition", "region": "EMEA", "role": "Mid", "champs": ["Syndra", "Orianna"], "account": "Simpli#EUW", "photo_url": ""},
    {"name": "SiuLoong", "team": "MGN Vikings Esports", "region": "LCP", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "SiuLoong#VCS", "photo_url": ""},
    {"name": "Siwoo", "team": "Dplus KIA", "region": "LCK", "role": "Top", "champs": ["K'Sante", "Renekton"], "account": "Siwoo#KR1", "photo_url": ""},
    {"name": "SkewMond", "team": "G2 Esports", "region": "LEC", "role": "Jungle", "champs": ["Vi", "Lee Sin"], "account": "G2 SkewMond#3327", "photo_url": ""},
    {"name": "Sniper", "team": "100 Thieves", "region": "LTAN", "role": "Top", "champs": ["Jax", "Fiora"], "account": "Sniper#NA1", "photo_url": ""},
    {"name": "Spica", "team": "Dignitas", "region": "LTAN", "role": "Jungle", "champs": ["Vi", "Lee Sin"], "account": "Spica#NA1", "photo_url": ""},
    {"name": "Sponge", "team": "DRX", "region": "LCK", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Sponge#KR1", "photo_url": ""},
    {"name": "Srtty", "team": "Dignitas", "region": "LTAN", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Srtty#NA1", "photo_url": ""},
    {"name": "Starry", "team": "Oh My God", "region": "LPL", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "OMG Starry#2026", "photo_url": ""},
    {"name": "Steller", "team": "Team Secret", "region": "LCP", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Steller#VCS", "photo_url": ""},
    {"name": "Stend", "team": "Team Heretics", "region": "LEC", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "TH Stend#000", "photo_url": ""},
    {"name": "Supa", "team": "Movistar KOI", "region": "LEC", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "Supa#KOI", "photo_url": ""},
    {"name": "Taki", "team": "Team Secret", "region": "LCP", "role": "Support", "champs": ["Thresh", "Lulu"], "account": "Taki#VCS", "photo_url": ""},
    {"name": "Tangyuan", "team": "Royal Never Give Up", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Tangyuan#CN1", "photo_url": ""},
    {"name": "Targamas", "team": "Karmine Corp", "region": "LEC", "role": "Support", "champs": ["Rakan", "Pike"], "account": "Targamas#LEC", "photo_url": ""},
    {"name": "Taxvig", "team": "KAOS Esport", "region": "NLC", "role": "Jungle", "champs": ["Vi", "Jarvan IV"], "account": "Taxvig#NLC", "photo_url": ""},
    {"name": "Teddy", "team": "DRX", "region": "LCK", "role": "Bot", "champs": ["Ezreal", "Jinx"], "account": "Teddy#KR1", "photo_url": ""},
    {"name": "Thanatos", "team": "Cloud9 Kia", "region": "LTAN", "role": "Top", "champs": ["Gnar", "Jax"], "account": "C9 Thanatos#KR2", "photo_url": ""},
    {"name": "Thayger", "team": "Barça Esports", "region": "EMEA", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Thayger#EUW", "photo_url": ""},
    {"name": "TheShy", "team": "Retired", "region": "LPL", "role": "Top", "champs": ["Fiora", "Jayce"], "account": "TheShy#CN1", "photo_url": ""},
    {"name": "Tian", "team": "Weibo Gaming Faw Audi", "region": "LPL", "role": "Jungle", "champs": ["Lee Sin", "Viego"], "account": "Tian#CN1", "photo_url": ""},
    {"name": "Tianzhen", "team": "Xi'an Team WE", "region": "LPL", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Tianzhen#CN1", "photo_url": ""},
    {"name": "tinowns", "team": "LOUD", "region": "LTAS", "role": "Mid", "champs": ["Azir", "Sylas"], "account": "tinowns#BR2", "photo_url": ""},
    {"name": "TitaN", "team": "paiN Gaming", "region": "LTAS", "role": "Bot", "champs": ["Aphelios", "Varus"], "account": "TitaN#BR1", "photo_url": ""},
    {"name": "TolanD", "team": "Beşiktaş Esports", "region": "TCL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "TolanD#TCL", "photo_url": ""},
    {"name": "Tomo", "team": "Dignitas", "region": "LTAN", "role": "Bot", "champs": ["Lucian", "Xayah"], "account": "Tomo#NA1", "photo_url": ""},
    {"name": "Tracyn", "team": "Team Heretics", "region": "LEC", "role": "Support", "champs": ["Nautilus", "Rakan"], "account": "Tracyn#LEC", "photo_url": ""},
    {"name": "Treatz", "team": "Team NORD", "region": "NLC", "role": "Support", "champs": ["Thresh", "Rakan"], "account": "Treatz#NLC", "photo_url": ""},
    {"name": "Tutsz", "team": "FURIA", "region": "LTAS", "role": "Mid", "champs": ["Azir", "Sylas"], "account": "Tutsz#1612", "photo_url": ""},
    {"name": "UmTi", "team": "Team Liquid Honda", "region": "LTAN", "role": "Jungle", "champs": ["Vi", "Lee Sin"], "account": "TL UmTi#0602", "photo_url": ""},
    {"name": "Upset", "team": "Karmine Corp", "region": "LEC", "role": "Bot", "champs": ["Kaisa", "Xayah"], "account": "Upset#LEC", "photo_url": ""},
    {"name": "Vampire", "team": "Xi'an Team WE", "region": "LPL", "role": "Support", "champs": ["Rakan", "Leona"], "account": "Vampire#CN1", "photo_url": ""},
    {"name": "Velja", "team": "Los Ratones", "region": "NLC", "role": "Jungle", "champs": ["Jarvan IV", "Vi"], "account": "VELJA DEL REY#2203", "photo_url": ""},
    {"name": "Viper", "team": "Hanwha Life Esports", "region": "LCK", "role": "Bot", "champs": ["Lucian", "Kai'Sa"], "account": "Viper#KR1", "photo_url": ""},
    {"name": "Vizicsacsi", "team": "NORD Esports", "region": "NLC", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "EWI Vizicsacsi#TOP", "photo_url": ""},
    {"name": "Vladi", "team": "Karmine Corp", "region": "LEC", "role": "Mid", "champs": ["Ahri", "Azir"], "account": "Vladi#LEC", "photo_url": ""},
    {"name": "Wako", "team": "Ultra Prime", "region": "LPL", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Wako#CN1", "photo_url": ""},
    {"name": "Way", "team": "KT Rolster", "region": "LCK", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Way#KR1", "photo_url": ""},
    {"name": "Wei", "team": "Royal Never Give Up", "region": "LPL", "role": "Jungle", "champs": ["Lee Sin", "Viego"], "account": "Wei#CN1", "photo_url": ""},
    {"name": "Weiwei", "team": "Suzhou LNG Ninebot Esports", "region": "LPL", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Weiwei#CN1", "photo_url": ""},
    {"name": "White", "team": "Unicorns of Love Sexy Edition", "region": "EMEA", "role": "Jungle", "champs": ["Lee Sin", "Sejuani"], "account": "White#EUW", "photo_url": ""},
    {"name": "whiteinn", "team": "Barça Esports", "region": "EMEA", "role": "Support", "champs": ["Rakan", "Leona"], "account": "whiteinn#EUW", "photo_url": ""},
    {"name": "WhiteKnight", "team": "Barça Esports", "region": "EMEA", "role": "Top", "champs": ["Gnar", "Renekton"], "account": "WhiteKnight#EUW", "photo_url": ""},
    {"name": "Winsome", "team": "LOUD", "region": "LTAS", "role": "Support", "champs": ["Rakan", "Thresh"], "account": "Winsome#BR1", "photo_url": ""},
    {"name": "Wiz", "team": "LOUD", "region": "LTAS", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "Wiz#BR1", "photo_url": ""},
    {"name": "Wizer", "team": "paiN Gaming", "region": "LTAS", "role": "Top", "champs": ["Gnar", "Fiora"], "account": "Wizer#BR1", "photo_url": ""},
    {"name": "WNTR", "team": "Lundqvist Lightside", "region": "NLC", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "404 WNTR#j0b", "photo_url": ""},
    {"name": "Woody", "team": "Talon", "region": "LCP", "role": "Support", "champs": ["Nautilus", "Leona"], "account": "Woody#PCS", "photo_url": ""},
    {"name": "Xiaohao", "team": "EDward Gaming Hycan", "region": "LPL", "role": "Jungle", "champs": ["Vi", "Sejuani"], "account": "Xiaohao#CN1", "photo_url": ""},
    {"name": "Xiaohu", "team": "Weibo Gaming Faw Audi", "region": "LPL", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "SuperMochi#1234", "photo_url": ""},
    {"name": "Xiaoxu", "team": "Royal Never Give Up", "region": "LPL", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Xiaoxu#CN1", "photo_url": ""},
    {"name": "xMatty", "team": "Team NORD", "region": "NLC", "role": "Bot", "champs": ["Ezreal", "Kai'Sa"], "account": "xMatty#NLC", "photo_url": ""},
    {"name": "xqw", "team": "LGD Gaming", "region": "LPL", "role": "Support", "champs": ["Thresh", "Nautilus"], "account": "xqw#CN1", "photo_url": ""},
    {"name": "XUN", "team": "JDG Intel Esports", "region": "LPL", "role": "Jungle", "champs": ["Lee Sin", "Vi"], "account": "XUN#CN1", "photo_url": ""},
    {"name": "Ycx", "team": "LGD Gaming", "region": "LPL", "role": "Top", "champs": ["K'Sante", "Gnar"], "account": "Ycx#CN1", "photo_url": ""},
    {"name": "Yeon", "team": "Team Liquid Honda", "region": "LTAN", "role": "Bot", "champs": ["Lucian", "Zeri"], "account": "Yeon#NA1", "photo_url": ""},
    {"name": "Yike", "team": "Karmine Corp", "region": "LEC", "role": "Jungle", "champs": ["Vi", "Viego"], "account": "Yike#LEC", "photo_url": ""},
    {"name": "Zeka", "team": "Hanwha Life Esports", "region": "LCK", "role": "Mid", "champs": ["Azir", "Orianna"], "account": "Zeka#KR1", "photo_url": ""},
    {"name": "ShowMaker", "team": "Dplus KIA", "region": "LCK", "role": "Mid", "champs": ["Azir", "LeBlanc"], "account": "Syndra#0722", "photo_url": ""},
    {"name": "Hans Sama", "team": "G2 Esports", "region": "LEC", "role": "Bot", "champs": ["Kalista", "Draven"], "account": "G2 Hans Sama#12838", "photo_url": ""},
    {"name": "Zeyzal", "team": "Shopify Rebellion", "region": "LTAN", "role": "Support", "champs": ["Thresh", "Braum"], "account": "Zeyzal#NA1", "photo_url": ""},
    {"name": "Zhuo", "team": "Suzhou LNG Ninebot Esports", "region": "LPL", "role": "Support", "champs": ["Rakan", "Leona"], "account": "Zhuo#CN1", "photo_url": ""},
    {"name": "Zika", "team": "Suzhou LNG Ninebot Esports", "region": "LPL", "role": "Top", "champs": ["Renekton", "Gnar"], "account": "Zika#CN1", "photo_url": ""},
    {"name": "Zuhy", "team": "KAOS Esport", "region": "NLC", "role": "Top", "champs": ["Gnar", "Jax"], "account": "Zuhy#NLC", "photo_url": ""},
    {"name": "Zven", "team": "Cloud9 Kia", "region": "LTAN", "role": "Support", "champs": ["Thresh", "Braum"], "account": "Zven#S16XD", "photo_url": ""},
]
